FROM ubuntu:18.04

RUN apt-get update &&\
    apt-get install -y autoconf automake libtool curl make g++ unzip

COPY protobuf-cpp-3.11.2.tar.gz /root/
RUN tar xzf /root/protobuf-cpp-3.11.2.tar.gz -C /usr/local/ &&\
    ln -s /usr/local/protobuf-3.11.2 /usr/local/protobuf

WORKDIR /usr/local/protobuf
RUN ./autogen.sh
RUN ./configure
RUN make
RUN make check
RUN make install && ldconfig
